GET localhost:8080/

###
GET  http://localhost:8080/api/content

###
GET http://localhost:8080/api/content/1

###
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "title": "Second Content",
  "description": "This is the second content",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-10-13T19:11:06.490704",
  "dateUpdated": "2024-10-13T19:12:06.490704",
  "url": "http://example.com"
}

###
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "Forth Content",
  "description": "This is the second content",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-10-13T19:11:06.490704",
  "dateUpdated": "2024-10-13T19:12:06.490704",
  "url": "http://example.com"
}

###
DELETE http://localhost:8080/api/content/1








